Update __init__.py
scidsg/frontpage pull request #35
Opened 2024-03-19 17:05 UTC by glenn-sorrentino

Include "Greenhouse Project" in list of article types.

2024-03-20 21:14 UTC, brassy-endomorph commented
We probably want to just add a CLI tool or web UI route for adding article types. And in fact we probably eventually want to remove the autopopulation on the assumption that a random user of this as a FOSS tool wouldn't want our article types. I can direct you on that if you want.

2024-03-24 20:45 UTC, glenn-sorrentino commented
> We probably want to just add a CLI tool or web UI route for adding article types. And in fact we probably eventually want to remove the autopopulation on the assumption that a random user of this as a FOSS tool wouldn't want our article types. I can direct you on that if you want.

Added a CLI tool to create new article types. I rebased, and it added a few files that already exist in the main repo.

2024-03-25 10:46 UTC, brassy-endomorph requested changes

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/add_type.py
> +if len(sys.argv) < 2:
This should be added using `click` and not as a standalone script.

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/add_type.py
> +conn = sqlite3.connect("/instance/your_database.db")
If you use `click`, you can just import `frontpage.db.db` and use that without having to manually create a connection. It will then accept the same connection string used for the rest of the app. As configured here, this is error prone.

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/add_type.py
> +c.execute(
Scripts like this shouldn't execute DDL. If the table doesn't exist, something is critically wrong, and the exception should be raise.

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/add_type.py
> +    c.execute("INSERT INTO article_types (type_name) VALUES (?)", (article_type_name,))
Since we use SqlAlchemy, we should use the models here.

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/add_type.py
> +    print(f"Article type '{article_type_name}' has been added successfully.")
If you're single quoting the variable to differentiate it from the rest of the text, you should use the `repr` format like: `"Article type {article_type_name!r} ..."`

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/add_type.py
> +except sqlite3.IntegrityError as e:
Catching the script prevents the exception from being raised which means the script will exit 0 on error. This is undesirable generally. It's better to just let the error fully surface for now so we get a stacktrace. If we very carefully caught the error on exactly the unique key's constraint, then printing this message and exiting 1 would be appropriate, but as this is, it will hide potential bugs.

2024-03-25 10:46 UTC, brassy-endomorph commented on frontpage/routes.py
> +        format_size(int(article.download_size)) if article.download_size else None
This will need to be rebased away after your other PR is merged

2024-04-18 20:20 UTC, glenn-sorrentino commented on frontpage/add_type.py
> +if len(sys.argv) < 2:
- added `click` and a `cli.py` file. 
- updated `__init__.py`

2024-04-18 20:25 UTC, glenn-sorrentino commented on frontpage/add_type.py
> +conn = sqlite3.connect("/instance/your_database.db")
👍

2024-04-18 20:34 UTC, glenn-sorrentino commented on frontpage/add_type.py
> +c.execute(
Centralized the functionality into `__init__.pt`

2024-04-18 20:36 UTC, glenn-sorrentino commented on frontpage/add_type.py
> +    print(f"Article type '{article_type_name}' has been added successfully.")
👍

2024-04-18 20:50 UTC, glenn-sorrentino commented on frontpage/add_type.py
> +except sqlite3.IntegrityError as e:
👍

2024-04-18 20:52 UTC, glenn-sorrentino commented on frontpage/routes.py
> +        format_size(int(article.download_size)) if article.download_size else None
👍

2024-04-18 20:58 UTC, glenn-sorrentino commented on frontpage/add_type.py
> +    c.execute("INSERT INTO article_types (type_name) VALUES (?)", (article_type_name,))
👍

2024-04-22 22:29 UTC, merged