Integrate Docker
scidsg/frontpage pull request #37
Opened 2024-04-16 01:36 UTC by glenn-sorrentino

Tested working locally

Created `Dockerfile` that follows our latest installer script as a template.

2024-04-16 18:52 UTC, brassy-endomorph requested changes

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +    nginx
We don't need `nginx`. The container will run a single process (`gunicorn`) and expose that. We'll use something like a docker-native reverse proxy (`traefik` most likely) to handle routing.

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +    git \
Why is `git` needed?

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +RUN rm -rf venv && virtualenv venv
Don't use a `venv` in the container. Just install the packages directly.

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +    poetry export --only main -f requirements.txt --output requirements.txt && \
You should look up the [builder pattern](https://docs.docker.com/build/building/multi-stage/). First stage just install `poetry` and export the requirements. Second stage copies the generated `requirements.txt` the use that to install, and do so directly with `pip` and not `poetry`. Poetry shouldn't be needed at all in the final container.

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +RUN touch .env && \
Containers shouldn't create state like this. The `.env` file can be mounted as a read-only volume, but more ideally you'd launch the container with the `env_file` configuration.

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +RUN chown -R www-data:www-data /frontpage && \
You shouldn't create directories like this. These directories are going to be mounted volumes when the container runs, and all their properties should be set external to the container.

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +RUN apt-get install nginx -y && \
Second `nginx` install?

2024-04-16 18:52 UTC, brassy-endomorph commented on Dockerfile
> +CMD ["sh", "-c", ". venv/bin/activate && gunicorn --bind 0.0.0.0:5000 frontpage:app & nginx -g 'daemon off;'"]
Running `sh -c 'command_1 & command_2'` is bad practice. If the `gunicorn` process crashes, we'll never know. Containers should only ever have one process, and when that "goes wrong" it should exit and the orchestrator (docker swarm, kubernetes) should handle restarting or whatever.

2024-04-16 23:22 UTC, glenn-sorrentino commented on Dockerfile
> +    git \
Left over from old code.

2024-04-16 23:29 UTC, glenn-sorrentino commented on Dockerfile
> +RUN rm -rf venv && virtualenv venv
👍

2024-04-16 23:38 UTC, glenn-sorrentino commented on Dockerfile
> +    poetry export --only main -f requirements.txt --output requirements.txt && \
👍

2024-04-16 23:46 UTC, glenn-sorrentino commented on Dockerfile
> +RUN apt-get install nginx -y && \
👍

2024-04-17 04:55 UTC, glenn-sorrentino commented on Dockerfile
> +CMD ["sh", "-c", ". venv/bin/activate && gunicorn --bind 0.0.0.0:5000 frontpage:app & nginx -g 'daemon off;'"]
👍

2024-04-17 05:43 UTC, glenn-sorrentino commented on Dockerfile
> +RUN touch .env && \
👍

2024-04-17 05:43 UTC, glenn-sorrentino commented on Dockerfile
> +RUN chown -R www-data:www-data /frontpage && \
👍

2024-04-17 05:43 UTC, glenn-sorrentino commented on Dockerfile
> +CMD ["sh", "-c", ". venv/bin/activate && gunicorn --bind 0.0.0.0:5000 frontpage:app & nginx -g 'daemon off;'"]
👍

2024-04-18 02:42 UTC, closed without merging