Search MVP
scidsg/frontpage pull request #49
Opened 2024-05-08 22:12 UTC by glenn-sorrentino

Here's a working search MVP that is simply a keyword search against a generated JSON file with the contents of the articles. 

No additional frameworks have been used, and I think we should wait to learn if we need a more robust search solution.

2024-05-10 19:00 UTC, brassy-endomorph requested changes

2024-05-10 19:00 UTC, brassy-endomorph commented on frontpage/static/script.js
> +            const filteredArticles = articles.filter(article =>
There's nothing wrong with this for "search" but it will break on so many trivial cases. Consider

- `cats` not having result for `cat`
- `cat dog` will only have results for the exact string `cat dog` but not docs about both cats and dogs
- `"cat"` (exact string search) won't work unless the quoted vesion appears in the text

These are all basic search queries people might expect to work. We should def use a framework

2024-05-10 19:05 UTC, glenn-sorrentino commented on frontpage/routes.py
> +@app.route("/generate_articles_json")
👍

2024-05-10 19:08 UTC, glenn-sorrentino commented on frontpage/routes.py
> +        except FileNotFoundError:
👍

2024-05-10 19:11 UTC, glenn-sorrentino commented on frontpage/routes.py
> +                "metadata": {
👍

2024-05-10 19:12 UTC, glenn-sorrentino commented on frontpage/routes.py
> +                    "slug": article.slug,
👍

2024-05-10 19:14 UTC, glenn-sorrentino commented on frontpage/routes.py
> +            json.dump(articles_data, f, indent=4)
👍

2024-05-11 21:28 UTC, glenn-sorrentino commented on frontpage/routes.py
> +        json_file_path = os.path.join(current_app.static_folder, "articles.json")
👍

2024-05-12 04:51 UTC, brassy-endomorph commented on frontpage/routes.py
> +        article_count = len(articles)
This variable is only used within the template. Passing both is redundant. The template should just grab the count itself.

2024-05-12 04:51 UTC, brassy-endomorph commented on frontpage/routes.py
> +            Article.title.ilike(f"%{query}%") | Article.content.ilike(f"%{query}%")
Doing `ilike` without escaping chars like `%` in the search string is going to have undesirable results

2024-05-12 04:51 UTC, brassy-endomorph commented on frontpage/routes.py
> +            Article.title.ilike(f"%{query}%") | Article.content.ilike(f"%{query}%")
But mostly we want to use something like one of these:

- https://lunrjs.com/docs/index.html
- http://elasticlunr.com/
- https://github.com/nextapps-de/flexsearch

2024-05-13 18:55 UTC, glenn-sorrentino commented on frontpage/routes.py
> +        article_count = 0
👍

2024-05-13 19:00 UTC, glenn-sorrentino commented on frontpage/routes.py
> +        article_count = len(articles)
👍

2024-05-14 21:38 UTC, glenn-sorrentino commented on .gitignore
> +frontpage/static/articles.json
👍

2024-05-14 22:15 UTC, glenn-sorrentino commented on frontpage/routes.py
> +            Article.title.ilike(f"%{query}%") | Article.content.ilike(f"%{query}%")
I'll open up a new ticket for integrating one of these libraries. I'm trying to integrate Lunr but its not as straightforward. I think we should merge the PR so we can have search while we continue with Lunr.

2024-05-14 22:16 UTC, glenn-sorrentino commented on frontpage/static/script.js
> +            const filteredArticles = articles.filter(article =>
same as comment below.

2024-05-14 22:16 UTC, merged